### ISSUE TITLE
Backup code formatting uses `LF` not `CRLF` in Windows

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#125]
From user testing:

> Downloading the backup recovery codes show as one long line in notepad in Windows. We encountered this with our security.txt file and found that it was because it was created with Linux line breaks which weren’t being recognised in Windows systems.

> The breaks do appear in Wordpad in Windows but most people will have notepad as their default program.

**Comment by ScopeyNZ** [comment]
Not sure if JS has some kind of API that indicates what kind of line ending are relevant for the current OS. Quick fix would be to use `CRLF` across the board.

**Comment by NightJar** [comment]
Good news, same thing happens in Linux.
Can replicate, will fix.

**Comment by NightJar** [comment]
OK neat. Changing from a dataURL built on the fly to the Blob and URL JS API solves the problem flat.

![image](https://user-images.githubusercontent.com/778003/59407493-74f98100-8e05-11e9-86b3-585b829640aa.png)

But the tests won't pass because Jest uses Enzyme to render, which uses JSDOM which doesn't support `URL.createObjectURL` - since at least 2017 when it was [reported](https://github.com/jsdom/jsdom/issues/1721).

I've tried monkey patching `global` before using the `shallow` render, and switching to `mount` didn't seem to change anything.

So I guess we could test from within the component itself as to wether `URL.createObjectURL` is set (and mock if it's not), but that seems rather gross. I'd prefer not to.
Does anyone have any ideas on how to proceed, like @Cheddam perhaps?

**Comment by robbieaverill** [comment]
Is the purpose of using this API to construct the href value more cleanly? Would an alternative be to replace `\n` with `\r\n` in the existing code? If there's a specific reason you need this API, does [this issue post](https://github.com/jsdom/jsdom/issues/1721#issuecomment-439222748) provide a workaround for the unit tests?

**Comment by NightJar** [comment]
> Is the purpose of using this API to construct the href value more cleanly?

No, it is because the previous code did not work in a wide enough set of cases.

> Would an alternative be to replace `\n` with `\r\n` in the existing code?

No, upon examination of the output in the downloading file it is observed that no separator was being inserted at all.

> If there's a specific reason you need this API, does [this issue post](https://github.com/jsdom/jsdom/issues/1721#issuecomment-439222748) provide a workaround for the unit tests?

I have tried this, in [various forms](https://github.com/silverstripe/silverstripe-mfa/compare/master...creative-commoners:pulls/4.0/download-preserve-line-end?expand=1#diff-3b08d2f25af04326846e185b4e276f34) (screenshot because I'll undoubtedly force push at some point, nullifying the link here).

![image](https://user-images.githubusercontent.com/778003/59408254-ba1eb280-8e07-11e9-9a36-f625fc604dc7.png)
