### ISSUE TITLE
Loading a method register screen from "Select a verification method" needs a loading indicator

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#133]
If you emulate a slow 3G network it becomes obvious that we need a loading indicator while the method's registration component loads its schema and renders itself:

https://screencast-o-matic.com/watch/cqh0coTXFq

**Comment by newleeland** [comment]
Good spotting. Perhaps we would be able to use the same loading indicator that we are using with the security key setup? https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321188000

A loading indicator would also hold the space, rather than see the modal collapsing and scaring people that they broke something.

**Comment by ScopeyNZ** [comment]
This is fixed now. The CSS for loading indicators was previously not included in the CMS stylesheet.
