### ISSUE TITLE
Move "reset MFA" endpoint to AdminRegistrationController

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#148]
The MFA reset endpoint is `admin/security/reset/[memberID]`. If we move the logic to AdminRegistrationController it would become `admin/mfa/reset/[MemberID]` which is less ambiguous in the context of `admin/security`

**Comment by Cheddam** [comment]
Thoughts on this:

- It was purposefully built to be generic / independent of MFA, so that it could be extracted into core or a polyfill module later
- _However_, without MFA (or some other additional factor that can be reset), this feature is nigh-identical to the existing Password Reset flow, so it may not be worth extracting after all

I don't feel strongly either way at the moment.

**Comment by ScopeyNZ** [comment]
Hmmmn good point. I think it makes sense as it is now. It is similar to the password reset feature with the important detail that it's triggered by the admin and mandatory (rather than by the user and optional).

**Comment by ScopeyNZ** [comment]
I'll close. If either of you feel strongly we can re-open 😄
