### ISSUE TITLE
Pressing enter when focussed on a member's password field in their profile triggers an Account Reset action

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-mfa#163]
As described, edit a profile, focus a password field and press enter. It triggers a MFA reset action instead of the page save action.

**Comment by robbieaverill** [comment]
For reference this also happens if you have an UploadField in a DataObject that is rendered in a GridFieldDetailForm, so it's not specific to this module.

**Comment by Cheddam** [comment]
@robbieaverill I can't actually reproduce this 🤔[This issue](https://github.com/silverstripe/silverstripe-mfa/issues/211) is admittedly making it harder to get a clear result, but I can't see any reason why a reset action would be triggered - the buttons in the MFA settings field are all marked as `type="button"`. Maybe this was fixed with a recent change?

**Comment by robbieaverill** [comment]
It seems to happen when you create a new member and then change their password after initially saving it.
