### ISSUE TITLE
[Demo review] Require password change checkbox appears to uncheck on save

### ISSUE THREAD

**Issue by newleeland** [silverstripe/silverstripe-mfa#178]
![Admin requiring user to change password on next login](https://user-images.githubusercontent.com/8085295/59228933-2f825b80-8c2d-11e9-8cad-f295ccc04975.png)

A admin can change the password of a user in the CMS and **requires them to change their password on next login**. However, upon saving the the checkbox is no longer checked, which can be confusing. However it also makes sense to have the checkbox reset as well, so it could be used again.

**Comment by robbieaverill** [comment]
@newleeland we discussed moving the checkbox yesterday in person and decided to keep it where it is now, because you may way to flag the account for mandated password reset without having to put a password in yourself as well - do you still agree with that?

The bug is that it doesn't retain its saved state, so we should fix that.

**Comment by newleeland** [comment]
From the discussions with @clarkepaul @brynwhyman, there isn't really a scenario where would want the admin to require the user to have a new password on next login, unless the admin has changed the user's password. Hence we think this issue can be resolved by having the checkbox within the accordion.

**Comment by NightJar** [comment]
resolved in https://github.com/silverstripe/silverstripe-security-extensions/pull/6
