### ISSUE TITLE
Specify a 'Lead In Label' for registration on MFA methods

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-mfa#216]
MFA methods are required to provide a name for registration (`RegisterHandlerInterface::getName()`) and for verification a 'lead in label' (`VerifyHandlerInterface::getLeadInLabel()`). Currently we use the name as part of the heading during the registration process for a method, but for consistency and the best translation experience, we should also ask for a 'lead in label' on `RegisterHandlerInterface` to use instead.

ACs:

- [ ] RegistrationHandlerInterface expects a lead in label
- [ ] The lead in label is passed through and used for the heading in the Registration UI
- [ ] The TOTP and WebAuthn modules are updated to conform to the new interface requirement

PRs:

- #251 
- silverstripe/silverstripe-totp-authenticator#27
- silverstripe/silverstripe-webauthn-authenticator#49

**Comment by robbieaverill** [comment]
Totally, let's get this in before stable

**Comment by ScopeyNZ** [comment]
Currently for strings returned by PHP we have:

- `VerifyHandlerInterface`
  - `getLeadInLabel`: "Verify with security key"
- `RegisterHandlerInterface`
  - `getName`: "Security key"
  - `getDescription`: "A small USB device which is used for verifying you"

I sort of think the distinction is okay here? I'm not sure that `getLeadInLabel` makes sense as a replacement for `getName` because it's used under the heading "Select a verification method". The "lead in label" for verification is used in a list of links where having a bit more of a "lead in" makes sense?

**Comment by Cheddam** [comment]
It's not intended to be a replacement for getName - but, we could probably use `i18n.inject` to achieve the same effect. The issue here is that we're expecting to output "Register with Security key" as the heading of the UI, but right now we just output the name "Security key". This needs to be changed, in an i18n-friendly way, and my suggestion was to match the behaviour of the Verify handler / UI. Ultimately I'm happy with either approach - whichever makes the most sense.

**Comment by ScopeyNZ** [comment]
Perhaps we should move "name" to the parent interface and then translate both `Verify with {method}` and `Register with {method}` in the mfa module itself. Avoiding translation strings required by implementing interfaces.

**Comment by ScopeyNZ** [comment]
Ok I've implemented those changes in the linked PRs 🙂
