### ISSUE TITLE
Cherry pick commits to 3.x branches

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#260]
The back-porting work to SS3 for this and the authenticator modules started while changes were still being committed to the SS4 version. 

We'll need to cherry pick the remaining fixes back to the SS3 branches to ensure it includes the latest code.

**Comment by robbieaverill** [comment]
Usually we cherry pick rather than merge, but we have merged back into 3.0 a couple of times already. It would probably be easier to continue to do that TBH.

**Comment by NightJar** [comment]
Will resolve #275

**Comment by robbieaverill** [comment]
I've merged @ScopeyNZ's work with a small patch in https://github.com/silverstripe/silverstripe-mfa/pull/290. I marked one test as skipped for SS3 because it's failing, but the subject it tests works fine. We can fix this later.

I've also merged the other modules back into 3.0 and merged all modules 4.0 into master.
