### ISSUE TITLE
EnabledMembers report doesn't export calculated fields

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-mfa#443]
Report as seen in the CMS:
![image](https://user-images.githubusercontent.com/893117/149238076-2d05577c-496c-439e-bc44-f58c51d05aaa.png)

Report export example:
![image](https://user-images.githubusercontent.com/893117/149237869-9a75f80d-4f39-4b0c-a70d-e663110caa76.png)

It looks like the 'Registered methods' and 'Default method' columns don't export at all.

### PRs
- [x] https://github.com/silverstripe/silverstripe-mfa/pull/444

**Comment by emteknetnz** [comment]
Issue is that formatting isn't getting applied in the context of the GridFieldExportButton
https://github.com/silverstripe/silverstripe-framework/blob/4/src/Forms/GridField/GridFieldExportButton.php#L250

https://github.com/silverstripe/silverstripe-mfa/blob/4/src/Report/EnabledMembers.php#L99

The "Skipped registration" column is showing 0/1 instead of the formatted 'No'/'Yes' ... though this is functionally OK

**Comment by emteknetnz** [comment]
PR https://github.com/silverstripe/silverstripe-mfa/pull/444

**Comment by emteknetnz** [comment]
Linked PR has been merged, will probably be released around the same time as CMS 4.11 (likely Mar/Apr) - @madmatt let me know if you require this to be released sooner

**Comment by maxime-rainville** [comment]
Looks like this got fixed.
