### ISSUE TITLE
Accessway - move login form to the CMS

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#45]
### Overview
There's been strong suggestions to remove all website authentication away from the frontend site, and into a CMS looking login form. 

This isn't the first time this has been raised, but it's relevant as part of the MFA work as we currently come up with the change

### Benefits
- Frontend designers/developers do not need to be concerned with the styling of the site login form (especially when the majority of logins are for CMS access)
- Removes the dependancy of relying on a theme to inherit styles (and potentially break) the original login form template
- Create a consistent and professional gateway to log in to the CMS
- Allows for a 'cleaner' approach for implementing an MFA flow for a site, removing the requirement to inject an MFA app into the SS page template.

### Considerations
- It's unlikely we'll want to build this into core before MFA is released with 4.4.x - so it should be handled in it's own module (https://github.com/silverstripe/silverstripe-login-forms/)
- A configuration flag could be built to enable this 
- This should include all `security` frontend forms: forgot password, reset password, MFA registration, MFA login, etc.
- There are examples in the current MFA flow where users in the CMS are prompted for MFA again. This flow will need to be considered too.

### ACs
- Create the template
- Template includes the site name, SilverStripe logo
- The template can be called with the framework config settings - it's auto enabled when the MFA module is installed (with the login-forms module being a requirement of the MFA module)
- The MFA module plugs into this
- Overriding the original login form form project code should be taken into consideration

### Other options discussed
1. Retain existing login form, on successful login, direct to MFA screen injected in the same page template
2. Retain existing login form, on successful login, direct to MFA standalone screen
2. A login modal on top of the site. This would likely be difficult to guarantee compatibility with all sites.

**Comment by brynwhyman** [comment]
Couple of options being discussed:
1. MFA modal on top of the original login form
2. MFA app embedded in the place of the login form
3. Push to an 'external' CMS-like MFA app

**Comment by brynwhyman** [comment]
Wireframe for **Accessway**:
![image](https://user-images.githubusercontent.com/15868440/54795317-8de41180-4cb0-11e9-9c3e-082cf119a6db.png)

**Comment by Cheddam** [comment]
Thoughts on this for whoever picks it up:

- Make sure you extract and utilise the existing font stack from the Admin module (and if you get the chance, consider trying to split the typography styles into a separate bundle within Admin so that we can just reference them directly in the future)
- Garion will buy you a coffee every day for a week if you implement a dark mode with [`prefers-color-scheme`](https://css-tricks.com/dark-modes-with-css/). Given the simplicity of the UI, this shouldn't take a ton of extra effort (and since this is a progressive enhancement for extremely new browser versions, you could make use of CSS variables too 😉)
- The SiteTitle should be an H1, so any headings in MFA should shift down to H2 and below (and there's some styling in MFA to hide the first H1 on the page that will need removing)
- The 'Login to CMS' wording is a little presumptuous - should just be 'Login'

**Comment by NightJar** [comment]
Notes for self tomorrow: Adding the theme override for security works well in `init` - except that if the Security controller isn't the ultimately responsible party for handling the request (or that request isn't e.g. `login` or `lostpassword` which will be handled by this theme) then the user will receive an error instead of ... output.

**Comment by brynwhyman** [comment]
@silverstripeux made a comment about promoting the SilverStripe logo more in the final designs in this comment https://github.com/silverstripe/silverstripe-mfa/issues/36#issuecomment-479649020

@NightJar is currently working on this ticket if it make sense to review the logo now.

**Comment by NightJar** [comment]
I just had a chat with @clarkepaul and he seems pretty happy with the progress. A few tweaks to go, and "Maybe something with the logo" - but just striving to implement the "close enough" that Paul will OK for now (he doesn't want [the mockup](https://github.com/silverstripe/silverstripe-mfa/issues/45#issuecomment-475464453) followed exactly).

**Comment by NightJar** [comment]
PR: https://github.com/silverstripe/silverstripe-login-forms/pull/12
