### ISSUE TITLE
MFA cannot be disabled for site

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-mfa#88]
A user is unable to disable MFA for a site using the `mfa settings` checkbox in site settings.

To reproduce:
1. Access site settings, confirm `mfa settings` checkbox is unchecked
2. Have a user who has not skipped registration log in
3. Identify user is shown the MFA registration screen **(bug)**

Expected behaviour:
If the `mfa settings` is unchecked, no user will be presented with the mfa registration screen when logging in.

Version:
silverstripe/mfa  dev-master 7c5ccba

**Comment by brynwhyman** [comment]
Note that a user should still be able to register MFA methods through their user settings page.

**Comment by robbieaverill** [comment]
Discussed in person, definitely a bug, but also maybe we shouldn’t have an “enabled” option at all. If it’s installed it’s optional, and if you set it as required then it’s enforced

**Comment by clarkepaul** [comment]
We've had quite a few conversations on this already, I'm not sure of all the decisions which led to that anymore @robbieaverill. They might need to roll out MFA at an organisational timeframe rather than a development go-live (processes, keys etc, they might be transitioning from RealME or to/from other MFA services). 

This one of those things which it might help cater to a few edge cases but isn't essential so could drop off if it needs to (good comms could produce the same outcome). If this was a developer audience which didn't rely on govt. processes then I'd tend to agree with not having the extra control.

**Comment by robbieaverill** [comment]
Cool, we should fix it for now anyway

**Comment by robbieaverill** [comment]
PR at #97
